using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using ProjectEuler;

namespace ProjectEuler.Tests
{
    /// <summary>
    /// Class containing tests against the correct answer for each problem in Project Euler.
    /// </summary>
    public class ProjectEulerTester
    {
        /// <summary>
        /// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
        /// Find the sum of all the multiples of 3 or 5 below 1000.
        /// Answer: 233168
        /// </summary>
        [Test]
        public void Prob1()
        {
            Assert.AreEqual(233168, Problem1.Solve());
        }

        /// <summary>
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        /// Answer: 4613732
        /// </summary>
        [Test]
        public void Prob2()
        {
            Assert.AreEqual(4613732, Problem2.Solve());
        }

        /// <summary>
        /// The prime factors of 13195 are 5, 7, 13 and 29.
        /// What is the largest prime factor of the number 600851475143 ?
        /// Answer: 6857
        /// </summary>
        [Test]
        public void Prob3()
        {
            Assert.AreEqual(6857, Problem3.Solve());
        }
    }
}
