using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using ProjectEuler;

namespace ProjectEuler.Tests
{
    /// <summary>
    /// Class containing tests against the correct answer for each problem in Project Euler.
    /// </summary>
    public class ProjectEulerTester
    {
        /// <summary>
        /// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
        /// Find the sum of all the multiples of 3 or 5 below 1000.
        /// Answer: 233168
        /// </summary>
        [Test]
        public void Prob1()
        {
            Assert.AreEqual(233168, Problem1.Solve());
        }

        /// <summary>
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        /// Answer: 4613732
        /// </summary>
        [Test]
        public void Prob2()
        {
            Assert.AreEqual(4613732, Problem2.Solve());
        }

        /// <summary>
        /// The prime factors of 13195 are 5, 7, 13 and 29.
        /// What is the largest prime factor of the number 600851475143 ?
        /// Answer: 6857
        /// </summary>
        [Test]
        public void Prob3()
        {
            Assert.AreEqual(6857, Problem3.Solve());
        }

        /// <summary>
        /// A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
        /// Find the largest palindrome made from the product of two 3-digit numbers.
        /// Answer: 906609
        /// </summary>
        [Test]
        public void Prob4()
        {
            Assert.AreEqual(906609, Problem4.Solve());
        }

        /// <summary>
        /// 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
        /// What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
        /// Answer: 232792560
        /// </summary>
        [Test]
        public void Prob5()
        {
            Assert.AreEqual(232792560, Problem5.Solve());
        }

        /// <summary>
        /// The sum of the squares of the first ten natural numbers is 1^2 + 2^2 + ... + 10^2 = 385.
        /// The square of the sum of the first ten natural numbers is (1 + 2 + ... + 10)^2 = 3025.
        /// Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
        /// Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
        /// Answer: 25164150
        /// </summary>
        [Test]
        public void Prob6()
        {
            Assert.AreEqual(25164150, Problem6.Solve());
        }
    }
}
